#!/usr/bin/env python3

import os
from sys import argv, exit, path

from twython import Twython
from termcolor import colored


from analyzer import Analyzer

# absolute paths to lists
positives = os.path.join(path[0], "positive-words.txt")
negatives = os.path.join(path[0], "negative-words.txt")

# instantiate analyzer
analyzer = Analyzer(positives, negatives)

APP_KEY = os.environ['API_KEY']
APP_SECRET = os.environ['API_SECRET']


def main():

    if len(argv) != 2:
        
        print("Usage: ./tweets @screen_name")
        exit(1)
    
    twitter = Twython(APP_KEY, APP_SECRET, oauth_version=2)
    
    ACCESS_TOKEN = twitter.obtain_access_token()
    
    twitter = Twython(APP_KEY, access_token=ACCESS_TOKEN)
    
    results = twitter.get_user_timeline(screen_name=argv[1], count=50)
    
    for result in results:
        
        # analyze word
        score = analyzer.analyze(result["text"])
        if score > 0.0:
            print(colored(str(score) + " " +result["text"], "green"))
        elif score < 0.0:
            print(colored(str(score) + " " +result["text"], "red"))
        else:
            print(colored(str(score) + " " +result["text"], "yellow"))
        
        
    
        


if __name__ == "__main__":
    main()